// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu2i464uqqJaY6CGePPKXk2vX4hfbPAu8',
    appId: '1:485553180730:web:463426a218ff6f70a36503',
    messagingSenderId: '485553180730',
    projectId: 'quiz-quest-f6baa',
    authDomain: 'quiz-quest-f6baa.firebaseapp.com',
    storageBucket: 'quiz-quest-f6baa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu2i464uqqJaY6CGePPKXk2vX4hfbPAu8',
    appId: '1:485553180730:android:463426a218ff6f70a36503',
    messagingSenderId: '485553180730',
    projectId: 'quiz-quest-f6baa',
    storageBucket: 'quiz-quest-f6baa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu2i464uqqJaY6CGePPKXk2vX4hfbPAu8',
    appId: '1:485553180730:ios:463426a218ff6f70a36503',
    messagingSenderId: '485553180730',
    projectId: 'quiz-quest-f6baa',
    storageBucket: 'quiz-quest-f6baa.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu2i464uqqJaY6CGePPKXk2vX4hfbPAu8',
    appId: '1:485553180730:ios:463426a218ff6f70a36503',
    messagingSenderId: '485553180730',
    projectId: 'quiz-quest-f6baa',
    storageBucket: 'quiz-quest-f6baa.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu2i464uqqJaY6CGePPKXk2vX4hfbPAu8',
    appId: '1:485553180730:web:463426a218ff6f70a36503',
    messagingSenderId: '485553180730',
    projectId: 'quiz-quest-f6baa',
    authDomain: 'quiz-quest-f6baa.firebaseapp.com',
    storageBucket: 'quiz-quest-f6baa.firebasestorage.app',
  );
}
